import { ISplitPath } from "../types/path";
import { IRouterPageName, IRouterConcept, IRouterMiddleware, IRouterPage, IRouterPageOptions, IRouterFetcher, RouterProtocolHandlerType } from "../types/router";
export declare class RouterConcept implements IRouterConcept {
    private prefix_;
    private origin_;
    private markers_;
    private onEvent_;
    private checkpoint_;
    private active_;
    private middlewares_;
    private fetchers_;
    private protocolHandlers_;
    private pages_;
    private current_;
    constructor(prefix_?: string, origin_?: string);
    SetPrefix(prefix: string): void;
    AddMiddleware(middleware: IRouterMiddleware): void;
    RemoveMiddleware(middleware: IRouterMiddleware | string): void;
    AddFetcher(fetcher: IRouterFetcher): void;
    RemoveFetcher(fetcher: IRouterFetcher): void;
    AddProtocolHandler(handler: RouterProtocolHandlerType): void;
    RemoveProtocolHandler(handler: RouterProtocolHandlerType): void;
    AddPage({ path, ...rest }: IRouterPageOptions): string;
    RemovePage(page: string | IRouterPageName): {
        id: string;
        path: string | RegExp;
        name?: string | undefined;
        title?: string | undefined;
        middleware?: string | string[] | undefined;
        cache?: boolean | undefined;
    } | null;
    FindPage(page: string | IRouterPageName): IRouterPage | null;
    FindMatchingPage(path: string): IRouterPage | null;
    Mount(load?: boolean): void;
    Goto(path: string | ISplitPath | IRouterPageName, shouldReload?: boolean): void;
    Reload(): void;
    GetCurrentPath(): string;
    GetActivePage(): IRouterPage | null;
    private Load_;
    private DoLoad_;
    private SetActiveState_;
}
